CXX=clang++
CXXFLAGS=-O0 -g -std=c++17 -Wall -I./src/components
LDFLAGS=
LDLIBS=-libverbs -lpmem -lpthread

TARGET_DIR=./target
TARGET=$(TARGET_DIR)/hill
OBJ_DIR=./obj
SRC_DIR=./src
COMPONENTS_DIR=./src/components

SRC_HILL=./src/hill.cpp
SRC_MAIN=./src/main.cpp
SRC_INDEXING_INDEXING=./src/components/indexing/indexing.cpp
SRC_COLORING_COLORING=./src/components/coloring/coloring.cpp
SRC_KV_PAIR_KV_PAIR=./src/components/kv_pair/kv_pair.cpp
SRC_TESTS_TESTS=./src/components/tests/tests.cpp
SRC_WAL_WAL=./src/components/wal/wal.cpp
SRC_CMD_PARSER_CMD_PARSER=./src/components/cmd_parser/cmd_parser.cpp
SRC_REMOTE_MEMORY_REMOTE_MEMORY=./src/components/remote_memory/remote_memory.cpp
SRC_RDMA_RDMA=./src/components/rdma/rdma.cpp
SRC_CLUSTER_CLUSTER=./src/components/cluster/cluster.cpp
SRC_MEMORY_MANAGER_MEMORY_MANAGER=./src/components/memory_manager/memory_manager.cpp
SRC_READ_CACHE_READ_CACHE=./src/components/read_cache/read_cache.cpp
SRC_ENGINE_ENGINE=./src/components/engine/engine.cpp
SRC_MISC_MISC=./src/components/misc/misc.cpp
SRC_TEST_CACHE=./tests/test_cache.cpp
SRC_TEST_MEMORY_MANAGER=./tests/test_memory_manager.cpp
SRC_TEST_POLYMORPHIC_POINTER=./tests/test_polymorphic_pointer.cpp
SRC_TEST_COLORING=./tests/test_coloring.cpp
SRC_TEST_WAL=./tests/test_wal.cpp
SRC_TEST_CMD_PARSER=./tests/test_cmd_parser.cpp
SRC_TEST_RDMA=./tests/test_rdma.cpp
SRC_TEST_KV_PAIR=./tests/test_kv_pair.cpp
SRC_TEST_ENGINE=./tests/test_engine.cpp
SRC_TEST_CLUSTER=./tests/test_cluster.cpp
SRC_TEST_MISC=./tests/test_misc.cpp
SRC_TEST_REMOTE_POINTER=./tests/test_remote_pointer.cpp

HDR_HILL=./src/hill.hpp
HDR_INDEXING_INDEXING=./src/components/indexing/indexing.hpp
HDR_COLORING_COLORING=./src/components/coloring/coloring.hpp
HDR_KV_PAIR_KV_PAIR=./src/components/kv_pair/kv_pair.hpp
HDR_TESTS_TESTS=./src/components/tests/tests.hpp
HDR_WAL_WAL=./src/components/wal/wal.hpp
HDR_CMD_PARSER_CMD_PARSER=./src/components/cmd_parser/cmd_parser.hpp
HDR_REMOTE_MEMORY_REMOTE_MEMORY=./src/components/remote_memory/remote_memory.hpp
HDR_RDMA_RDMA=./src/components/rdma/rdma.hpp
HDR_CLUSTER_CLUSTER=./src/components/cluster/cluster.hpp
HDR_MEMORY_MANAGER_MEMORY_MANAGER=./src/components/memory_manager/memory_manager.hpp
HDR_READ_CACHE_READ_CACHE=./src/components/read_cache/read_cache.hpp
HDR_ENGINE_ENGINE=./src/components/engine/engine.hpp
HDR_MISC_MISC=./src/components/misc/misc.hpp

OBJ_HILL=./obj/hill.o
OBJ_MAIN=./obj/main.o
OBJ_INDEXING_INDEXING=./obj/indexing_indexing.o
OBJ_COLORING_COLORING=./obj/coloring_coloring.o
OBJ_KV_PAIR_KV_PAIR=./obj/kv_pair_kv_pair.o
OBJ_TESTS_TESTS=./obj/tests_tests.o
OBJ_WAL_WAL=./obj/wal_wal.o
OBJ_CMD_PARSER_CMD_PARSER=./obj/cmd_parser_cmd_parser.o
OBJ_REMOTE_MEMORY_REMOTE_MEMORY=./obj/remote_memory_remote_memory.o
OBJ_RDMA_RDMA=./obj/rdma_rdma.o
OBJ_CLUSTER_CLUSTER=./obj/cluster_cluster.o
OBJ_MEMORY_MANAGER_MEMORY_MANAGER=./obj/memory_manager_memory_manager.o
OBJ_READ_CACHE_READ_CACHE=./obj/read_cache_read_cache.o
OBJ_ENGINE_ENGINE=./obj/engine_engine.o
OBJ_MISC_MISC=./obj/misc_misc.o
OBJ_TEST_CACHE=./obj/test_cache.o
OBJ_TEST_MEMORY_MANAGER=./obj/test_memory_manager.o
OBJ_TEST_POLYMORPHIC_POINTER=./obj/test_polymorphic_pointer.o
OBJ_TEST_COLORING=./obj/test_coloring.o
OBJ_TEST_WAL=./obj/test_wal.o
OBJ_TEST_CMD_PARSER=./obj/test_cmd_parser.o
OBJ_TEST_RDMA=./obj/test_rdma.o
OBJ_TEST_KV_PAIR=./obj/test_kv_pair.o
OBJ_TEST_ENGINE=./obj/test_engine.o
OBJ_TEST_CLUSTER=./obj/test_cluster.o
OBJ_TEST_MISC=./obj/test_misc.o
OBJ_TEST_REMOTE_POINTER=./obj/test_remote_pointer.o

OUT_OBJS=$(OBJ_HILL) $(OBJ_MAIN) $(OBJ_INDEXING_INDEXING) $(OBJ_COLORING_COLORING) $(OBJ_KV_PAIR_KV_PAIR) $(OBJ_WAL_WAL) $(OBJ_CMD_PARSER_CMD_PARSER) $(OBJ_REMOTE_MEMORY_REMOTE_MEMORY) $(OBJ_RDMA_RDMA) $(OBJ_CLUSTER_CLUSTER) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER) $(OBJ_READ_CACHE_READ_CACHE) $(OBJ_ENGINE_ENGINE) $(OBJ_MISC_MISC)
TEST_OBJS=$(OBJ_TESTS_TESTS) $(OBJ_TEST_CACHE) $(OBJ_TEST_MEMORY_MANAGER) $(OBJ_TEST_POLYMORPHIC_POINTER) $(OBJ_TEST_COLORING) $(OBJ_TEST_WAL) $(OBJ_TEST_CMD_PARSER) $(OBJ_TEST_RDMA) $(OBJ_TEST_KV_PAIR) $(OBJ_TEST_ENGINE) $(OBJ_TEST_CLUSTER) $(OBJ_TEST_MISC) $(OBJ_TEST_REMOTE_POINTER)

TEST_CACHE=./target/test_cache
TEST_MEMORY_MANAGER=./target/test_memory_manager
TEST_POLYMORPHIC_POINTER=./target/test_polymorphic_pointer
TEST_COLORING=./target/test_coloring
TEST_WAL=./target/test_wal
TEST_CMD_PARSER=./target/test_cmd_parser
TEST_RDMA=./target/test_rdma
TEST_KV_PAIR=./target/test_kv_pair
TEST_ENGINE=./target/test_engine
TEST_CLUSTER=./target/test_cluster
TEST_MISC=./target/test_misc
TEST_REMOTE_POINTER=./target/test_remote_pointer
TESTS=$(TEST_CACHE) $(TEST_MEMORY_MANAGER) $(TEST_POLYMORPHIC_POINTER) $(TEST_COLORING) $(TEST_WAL) $(TEST_CMD_PARSER) $(TEST_RDMA) $(TEST_KV_PAIR) $(TEST_ENGINE) $(TEST_CLUSTER) $(TEST_MISC) $(TEST_REMOTE_POINTER)

HILL_DEP=$(SRC_HILL) $(HDR_HILL)
MAIN_DEP=$(SRC_MAIN)
INDEXING_INDEXING_DEP=$(SRC_INDEXING_INDEXING) $(HDR_INDEXING_INDEXING)
COLORING_COLORING_DEP=$(SRC_COLORING_COLORING) $(HDR_COLORING_COLORING)
KV_PAIR_KV_PAIR_DEP=$(SRC_KV_PAIR_KV_PAIR) $(HDR_KV_PAIR_KV_PAIR) $(MEMORY_MANAGER_MEMORY_MANAGER_DEP)
TESTS_TESTS_DEP=$(SRC_TESTS_TESTS) $(HDR_TESTS_TESTS)
WAL_WAL_DEP=$(SRC_WAL_WAL) $(HDR_WAL_WAL) $(MEMORY_MANAGER_MEMORY_MANAGER_DEP)
CMD_PARSER_CMD_PARSER_DEP=$(SRC_CMD_PARSER_CMD_PARSER) $(HDR_CMD_PARSER_CMD_PARSER)
REMOTE_MEMORY_REMOTE_MEMORY_DEP=$(SRC_REMOTE_MEMORY_REMOTE_MEMORY) $(HDR_REMOTE_MEMORY_REMOTE_MEMORY) $(MEMORY_MANAGER_MEMORY_MANAGER_DEP) $(RDMA_RDMA_DEP) $(MISC_MISC_DEP)
RDMA_RDMA_DEP=$(SRC_RDMA_RDMA) $(HDR_RDMA_RDMA)
CLUSTER_CLUSTER_DEP=$(SRC_CLUSTER_CLUSTER) $(HDR_CLUSTER_CLUSTER) $(MISC_MISC_DEP) $(MEMORY_MANAGER_MEMORY_MANAGER_DEP)
MEMORY_MANAGER_MEMORY_MANAGER_DEP=$(SRC_MEMORY_MANAGER_MEMORY_MANAGER) $(HDR_MEMORY_MANAGER_MEMORY_MANAGER)
READ_CACHE_READ_CACHE_DEP=$(SRC_READ_CACHE_READ_CACHE) $(HDR_READ_CACHE_READ_CACHE) $(KV_PAIR_KV_PAIR_DEP) $(REMOTE_MEMORY_REMOTE_MEMORY_DEP)
ENGINE_ENGINE_DEP=$(SRC_ENGINE_ENGINE) $(HDR_ENGINE_ENGINE) $(WAL_WAL_DEP) $(REMOTE_MEMORY_REMOTE_MEMORY_DEP) $(CLUSTER_CLUSTER_DEP)
MISC_MISC_DEP=$(SRC_MISC_MISC) $(HDR_MISC_MISC)
TEST_CACHE_DEP=$(SRC_TEST_CACHE) $(HDR_TEST_CACHE) $(CMD_PARSER_CMD_PARSER_DEP)
TEST_MEMORY_MANAGER_DEP=$(SRC_TEST_MEMORY_MANAGER) $(HDR_TEST_MEMORY_MANAGER) $(MEMORY_MANAGER_MEMORY_MANAGER_DEP)
TEST_POLYMORPHIC_POINTER_DEP=$(SRC_TEST_POLYMORPHIC_POINTER) $(HDR_TEST_POLYMORPHIC_POINTER) $(REMOTE_MEMORY_REMOTE_MEMORY_DEP)
TEST_COLORING_DEP=$(SRC_TEST_COLORING) $(HDR_TEST_COLORING) $(COLORING_COLORING_DEP)
TEST_WAL_DEP=$(SRC_TEST_WAL) $(HDR_TEST_WAL) $(WAL_WAL_DEP)
TEST_CMD_PARSER_DEP=$(SRC_TEST_CMD_PARSER) $(HDR_TEST_CMD_PARSER) $(CMD_PARSER_CMD_PARSER_DEP)
TEST_RDMA_DEP=$(SRC_TEST_RDMA) $(HDR_TEST_RDMA) $(RDMA_RDMA_DEP) $(COLORING_COLORING_DEP) $(CMD_PARSER_CMD_PARSER_DEP) $(MISC_MISC_DEP)
TEST_KV_PAIR_DEP=$(SRC_TEST_KV_PAIR) $(HDR_TEST_KV_PAIR) $(KV_PAIR_KV_PAIR_DEP)
TEST_ENGINE_DEP=$(SRC_TEST_ENGINE) $(HDR_TEST_ENGINE) $(ENGINE_ENGINE_DEP) $(CMD_PARSER_CMD_PARSER_DEP)
TEST_CLUSTER_DEP=$(SRC_TEST_CLUSTER) $(HDR_TEST_CLUSTER) $(CLUSTER_CLUSTER_DEP) $(CMD_PARSER_CMD_PARSER_DEP)
TEST_MISC_DEP=$(SRC_TEST_MISC) $(HDR_TEST_MISC) $(MISC_MISC_DEP) $(CMD_PARSER_CMD_PARSER_DEP)
TEST_REMOTE_POINTER_DEP=$(SRC_TEST_REMOTE_POINTER) $(HDR_TEST_REMOTE_POINTER) $(REMOTE_MEMORY_REMOTE_MEMORY_DEP)

out: $(OUT_OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OUT_OBJS) $(LDFLAGS) $(LDLIBS)

test: $(TESTS)

all: out test

$(OBJ_HILL): $(HILL_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_HILL)

$(OBJ_MAIN): $(MAIN_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_MAIN)

$(OBJ_INDEXING_INDEXING): $(INDEXING_INDEXING_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_INDEXING_INDEXING)

$(OBJ_COLORING_COLORING): $(COLORING_COLORING_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_COLORING_COLORING)

$(OBJ_KV_PAIR_KV_PAIR): $(KV_PAIR_KV_PAIR_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_KV_PAIR_KV_PAIR)

$(OBJ_TESTS_TESTS): $(TESTS_TESTS_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TESTS_TESTS)

$(OBJ_WAL_WAL): $(WAL_WAL_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_WAL_WAL)

$(OBJ_CMD_PARSER_CMD_PARSER): $(CMD_PARSER_CMD_PARSER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_CMD_PARSER_CMD_PARSER)

$(OBJ_REMOTE_MEMORY_REMOTE_MEMORY): $(REMOTE_MEMORY_REMOTE_MEMORY_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_REMOTE_MEMORY_REMOTE_MEMORY)

$(OBJ_RDMA_RDMA): $(RDMA_RDMA_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_RDMA_RDMA)

$(OBJ_CLUSTER_CLUSTER): $(CLUSTER_CLUSTER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_CLUSTER_CLUSTER)

$(OBJ_MEMORY_MANAGER_MEMORY_MANAGER): $(MEMORY_MANAGER_MEMORY_MANAGER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_MEMORY_MANAGER_MEMORY_MANAGER)

$(OBJ_READ_CACHE_READ_CACHE): $(READ_CACHE_READ_CACHE_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_READ_CACHE_READ_CACHE)

$(OBJ_ENGINE_ENGINE): $(ENGINE_ENGINE_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_ENGINE_ENGINE)

$(OBJ_MISC_MISC): $(MISC_MISC_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_MISC_MISC)

$(OBJ_TEST_CACHE): $(TEST_CACHE_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_CACHE)

$(OBJ_TEST_MEMORY_MANAGER): $(TEST_MEMORY_MANAGER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_MEMORY_MANAGER)

$(OBJ_TEST_POLYMORPHIC_POINTER): $(TEST_POLYMORPHIC_POINTER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_POLYMORPHIC_POINTER)

$(OBJ_TEST_COLORING): $(TEST_COLORING_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_COLORING)

$(OBJ_TEST_WAL): $(TEST_WAL_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_WAL)

$(OBJ_TEST_CMD_PARSER): $(TEST_CMD_PARSER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_CMD_PARSER)

$(OBJ_TEST_RDMA): $(TEST_RDMA_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_RDMA)

$(OBJ_TEST_KV_PAIR): $(TEST_KV_PAIR_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_KV_PAIR)

$(OBJ_TEST_ENGINE): $(TEST_ENGINE_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_ENGINE)

$(OBJ_TEST_CLUSTER): $(TEST_CLUSTER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_CLUSTER)

$(OBJ_TEST_MISC): $(TEST_MISC_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_MISC)

$(OBJ_TEST_REMOTE_POINTER): $(TEST_REMOTE_POINTER_DEP)
	$(CXX) $(CXXFLAGS) -o $@ -c $(SRC_TEST_REMOTE_POINTER)

$(TEST_CACHE): $(OBJ_TEST_CACHE) $(OBJ_CMD_PARSER_CMD_PARSER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_MEMORY_MANAGER): $(OBJ_TEST_MEMORY_MANAGER) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_POLYMORPHIC_POINTER): $(OBJ_TEST_POLYMORPHIC_POINTER) $(OBJ_REMOTE_MEMORY_REMOTE_MEMORY) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER) $(OBJ_RDMA_RDMA) $(OBJ_MISC_MISC)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_COLORING): $(OBJ_TEST_COLORING) $(OBJ_COLORING_COLORING)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_WAL): $(OBJ_TEST_WAL) $(OBJ_WAL_WAL) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_CMD_PARSER): $(OBJ_TEST_CMD_PARSER) $(OBJ_CMD_PARSER_CMD_PARSER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_RDMA): $(OBJ_TEST_RDMA) $(OBJ_RDMA_RDMA) $(OBJ_COLORING_COLORING) $(OBJ_CMD_PARSER_CMD_PARSER) $(OBJ_MISC_MISC)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_KV_PAIR): $(OBJ_TEST_KV_PAIR) $(OBJ_KV_PAIR_KV_PAIR) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_ENGINE): $(OBJ_TEST_ENGINE) $(OBJ_ENGINE_ENGINE) $(OBJ_CMD_PARSER_CMD_PARSER) $(OBJ_WAL_WAL) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER) $(OBJ_REMOTE_MEMORY_REMOTE_MEMORY) $(OBJ_CLUSTER_CLUSTER) $(OBJ_RDMA_RDMA) $(OBJ_MISC_MISC)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_CLUSTER): $(OBJ_TEST_CLUSTER) $(OBJ_CLUSTER_CLUSTER) $(OBJ_MISC_MISC) $(OBJ_CMD_PARSER_CMD_PARSER) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_MISC): $(OBJ_TEST_MISC) $(OBJ_MISC_MISC) $(OBJ_CMD_PARSER_CMD_PARSER)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(TEST_REMOTE_POINTER): $(OBJ_TEST_REMOTE_POINTER) $(OBJ_REMOTE_MEMORY_REMOTE_MEMORY) $(OBJ_MEMORY_MANAGER_MEMORY_MANAGER) $(OBJ_RDMA_RDMA) $(OBJ_MISC_MISC)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)


.PHONY: clean
clean: 
	rm ./target/*
	rm ./obj/*.o
